name: Java-workflow1

on:
  push: 
    branches:
      - main 

jobs: 
  build:
    name: my-spc
    runs-on: self-hosted  

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2'
          distribution: 'temurin'

      - name: build Java with maven
        run: mvn package 